swisspost/apikana

src/generate.js
Sorry, previously directly changed on master...
=> Made complete API file use jsonchema v4 instead of v3

bin/apikana, src/generate-constants.js, src/generate-java-builder.js, src/generate-java-paths.js, src/params.js, src/url-utils.js
Drop leading slashes in paths using filter utility during java code
generation.
=> [#20] Drop leading slashes in 2nd gen paths

src/deps/helper.js
- Improved extraction of type name.
=> [#19] Fix: request body not docson-ized

package.json, src/generate-schema.js, test/src/ts/user.ts
- Empty array is not allowed for required attribute -> must be undefined if there are no required fields
=> [#26] Fixed required field bug

.editorconfig, .travis.yml, README.md, package-lock.json, package.json, test/jasmine.config.json, test/runner.js, test/specs/url-utils.spec.js
- Add jasmine@3.3.0.
- Setup jasmine config.
- Setup test script.
- Implement test for url-utils.
- Configured travis for tests.
- Add doc for testing in README.
- Fix some markdown syntax errors in README.
- Introduced editorconfig.
- Updated package-lock.json.
=> Setup test configuration for apikana

src/init/init.js
=> Moved plugin_packages directory to the os tmp dir

src/generate.js
=> Keep original folder structure

src/plopfile_init.js
Added generation of gitignore on init excluding dist/ and node_modules/ folders
=> Added generation of gitignore on init excluding dist and node_modules

src/generate.js
I'm not particularly happy with this solution but it does the job as expected. 
@lbovet: If you want another message just tell me and I'll change it.
=> Added loading message on swagger initialization

src/plopfile_init.js, src/plopfile_start.js
It seems that plop.js understands only the unix path separators...
=> Load also templates in apikana-defaults

src/generate.js, src/plopfile_start.js
Cleanup functionality should also be a gulp task and not a plop action.
=> Moved cleanup to gulp task

README.md, npm-shrinkwrap.json, package.json, src/plopfile_init.js
Updated readme
Allow usage without apikana-defaults
=> Release apikana 0.6.0

README.md, src/plopfile_start.js
Allow to define project internal templates
=> Project level templates

src/generate.js, src/log.js, src/plopfile_init.js, src/schema-gen.js, test/specs/generate.spec.js, test/specs/sandbox.js, test/specs/scaffold.spec.js
Create a sandbox module to test scaffolding (apikana init) and generation (apikana start) with Jasmine.
=> Test infrastructure

bin/apikana, npm-shrinkwrap.json, package.json, src/generate-sample.js, src/generate.js, src/scaffold/template/base/package.json, src/validate-samples.js
Added:
- apikana generate-sample [typeName]
- apikana validate-samples
=> Added generation and validation of samples

src/generate.js
Salut Laurent, could you please check the change? 
I didn't find any other way to let gulp copy the whole project structure at once. Thank you!
=> Copy all model directories to dist/ts

npm-shrinkwrap.json, package.json, src/generate-schema.js, src/generate.js, test/specs/generate.spec.js
Added complete json schema generation of root models
=> Standalone complete schema

src/generate-sample.js
Skip enum types while collecting all models
=> ignore enum while generating samples

npm-shrinkwrap.json, package.json, src/generate-sample.js
- enabled sample generation for optional values
=> Generate sample for optionals

src/generate.js
Otherwise XSD generation fails.
=> Generate full schema only for object types

package.json, src/plopfile_start.js
* Add conditional template helpers
=> Release 0.9.7

package.json, src/plopfile_start.js
* Add url encode helper for templates
=> Release 0.9.8

npm-shrinkwrap.json, package.json, src/generate.js
* Remove ids only in openapi files, keep it in full json schema
=> Release 0.9.12

npm-shrinkwrap.json, package.json
* Run sample validation upon publish
=> Release 0.9.13

package.json, src/generate-avro.js
=> Release 0.9.14

.gitignore, package.json, src/generate-avro.js, src/generate.js, src/plopfile_init.js
* Option to generate enums as strings in avro schema
=> Release 0.9.15

package.json, src/generate-sample.js
* Fix generation of samples with dependencies on Windows
=> Release 0.9.16

package.json, src/generate-avro.js
* Add support for maps of primitive types in generated avro schema
=> Release 0.9.17

bin/apikana
=> relative source path when defining api

package.json, src/generate.js, src/scaffold/template/base/.eslintrc.json, src/scaffold/template/stream/src/ts/pet-event.ts
Fixes:
- Allow leading underscore in property names
- Fix pet-event to not break linting
- Fix regression in complete API references
=> Release 0.9.20

README.md, npm-shrinkwrap.json, package.json, src/plopfile_init.js, src/plopfile_start.js, src/scaffold/template/maven/gen/maven/pom.xml, test/specs/generate.spec.js, test/specs/sandbox.js
=> finetune snapshot regex to capture only rc versions

README.md, npm-shrinkwrap.json, package.json, src/generate.js, src/plopfile_init.js, src/plopfile_start.js, src/scaffold/template/maven/gen/maven/pom.xml, test/specs/generate.spec.js, test/specs/sandbox.js
* Fix to make only the rc versions considered as maven snapshots. Allows for branch qualifiers in version.
=> Release 0.9.23

package.json, src/scaffold/template/base/src/ts/pet.ts, src/scaffold/template/rest/src/openapi/api.yaml, src/scaffold/template/stream/src/ts/pet-event.ts
Fixes in generated example:
- Namespace in URL
- Explicit ID naming
- Avoid anonymous types messing up dotnet generation
- Wrong array setting in REST response
=> Release 0.9.26

src/schema-migrate.js, test/specs/generate.spec.js
Prepend # in the converted draft07 json schema
=> Draft07 conversion fix

package.json, src/scaffold/template/base/src/ts/pet.ts, src/scaffold/template/rest/src/openapi/api.yaml, src/scaffold/template/stream/src/ts/pet-event.ts
Fix json schema latest $id value to start with hash # because of some validation issues: https://github.com/gregsdennis/json-everything/issues/225
=> Release 0.9.27

package.json, src/generate.js, src/plopfile_init.js
- fix: improved namespace question
- fix: draft7 migrator only for json-schema files
=> Release 0.9.28

README.md, package.json, src/generate.js
- fix: recursive types regression
=> Release 0.9.30

.github/workflows/build.yml, README.md
Contains updated docs and references. After merging this, we should transfer apikana to the new organization ;)
=> Swisspost migration
